import QtQuick
import QtPositioning
import QtLocation
import Qt.labs.qmlmodels 1.0

DelegateChooser {
    id: dc
    role: "type"

    property color defaultColor: "#46a2da"
    property real defaultOpacity: 0.6
    property Map map
    property geoCoordinate clickedCoordinate
    property geoCoordinate lowestCoordinate
    property geoCoordinate highestCoordinate

    // Features are explicitly not generated by the parser, but converted straight to their content + the properties.

    DelegateChoice {
        roleValue: "FeatureCollection"
        delegate: MapItemView {
            property string geojsonType: "FeatureCollection"
            property var props: modelData.properties
            model: modelData.data
            delegate: dc
        }
    }
}
